name: CMake on a single platform
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Update and install
        run: |
          docker pull pavelgr/optifostvision-development
   