name: CMake on a single platform
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-22.04
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.2'
          host: 'linux'
          target: 'desktop'
      - name: Check install QT
        run: find ${{env.QT_DIR}}
      - name: Check install Qt6
        run: find ${{env.Qt6_DIR}}
      - name: Update and install
        run: |
          sudo apt-get update -qq
          sudo apt-get install clang
  build:
    name: Build project
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      
      - name: Build project
        run: cmake --build build --config ${{ env.BUILD_TYPE }}
      # - name: Configure CMake
      #   run: |
      #     cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH=${{env.Qt6_Dir}}
      # - name: Build
      #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}